name: Documentation

on:
  push:
    branches:
      - documentation

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository: $GITHUB_WORKSPACE'
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs
          python3 -m pip install mkdocs-bootswatch
      
      - name: Build Docs
        run: mkdocs build
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./site
          publish_branch: master
